### ISSUE TITLE
4.0.1: missing git tag

### ISSUE THREAD

**Issue by kloczek** [rspeer/ordered-set#66]
Yep looks like still there is no git tag for that version oin git repo.

**Comment by baldurmen** [comment]
I've decided to package this library in Debian, and I will use the github tags for releases. Looking at the pypi history, I'm slightly worried about the missing git tags on github...

I would be great if you could push that missing 4.0.1 tag, at least it would reassure me :)

**Comment by rspeer** [comment]
Tags for 4.0.1 and 4.1.0 are pushed now.
