### ISSUE TITLE
Package is not PEP 561 compliant

### ISSUE THREAD

**Issue by kmkurn** [rspeer/ordered-set#72]
Hi, I notice that this package isn't PEP 561 compliant, making mypy (v0.782, Python 3.7) unable to detect type annotations even though they exist in the code. A remedy is to put a `py.typed` file in the package directory, as explained in https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages. I may be able to make a PR for this, so let me know if you're OK with it.

**Comment by Eric-Arellano** [comment]
Hey @kmkurn, FYI I tried implementing this in https://github.com/LuminosoInsight/ordered-set/pull/60 and we had to revert in https://github.com/LuminosoInsight/ordered-set/pull/65.

**Comment by kmkurn** [comment]
@Eric-Arellano Thanks for pointing that out! I think the issue can be avoided if the library is distributed as a package instead. What I have in mind is to make a directory named `ordered_set`, move the current `ordered_set.py` to `ordered_set/__init__.py`, and create `ordered_set/py.typed` (and of course adjusting `setup.py` accordingly). This should be backward compatible (e.g., `from ordered_set import OrderedSet` should still work) and doesn't pollute the `site-package` directory as in #60. Let me know what you think.

**Comment by Eric-Arellano** [comment]
That makes sense to me! ￼

I know the maintainer Robyn was also interested in how to better test that the built wheel works correctly. It'd be good to run setup.py and then test it all works. 

While I'm not the maintainer, I suspect it would be great to automate that too. Add to CI running `python setup.py bdist_wheel` and then do a smoke screen test that checks imports still work.

**Comment by asford** [comment]
@Eric-Arellano Is there a blocking factor behind #75 being merged to close this?

**Comment by Eric-Arellano** [comment]
I'm not sure. I'm not the maintainer of this project, only a user who follows it and has contributed a bit in the past. 

If not already done, it would be great with #75 to try building the wheel locally and ensuring that things work correctly, i.e. that we do not repeat the issues of #60.

**Comment by rspeer** [comment]
I said more about this on the PR, but this is something I'd rather revisit if there's a more compelling reason to repackage ordered-set. I'm too disappointed by the state of packaging of types to want to change the shape of this package for that alone.

**Comment by rspeer** [comment]
Fixed in 4.1. I had a more compelling reason to repackage ordered-set (using flit instead of setuptools), and now the package has a PEP561 compatible structure.
