### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [rspeer/ordered-set#74]
Wheels (`.whl`) for this package are [currently missing from PyPI](https://pypi.org/project/ordered-set/4.0.2/#files). Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by rspeer** [comment]
I'm looking into using Poetry, which would solve this problem more simply.

**Comment by rspeer** [comment]
Fixed by using Flit (per the recommendation of #82).
