### ISSUE TITLE
The __getitem__ type annotations are missing single int index overload.

### ISSUE THREAD

**Issue by KSneijders** [rspeer/ordered-set#81]
Thanks for this library. It works like a charm! 
I found a very minor 'issue'. Getting a single item isn't supported according to the type hints but it does function properly. 

![image](https://user-images.githubusercontent.com/32707500/147855531-31c10501-b6d1-4c75-93ae-d36d9b61331c.png)

^ Screenshot of code in PyCharm

This feature works properly (and is also shown in the docstring example). The reason it's not showing as type annotation is because there's no overload for it. Adding the 3 lines below resolves the 'issue'.

```py
@overload
def __getitem__(self, index: int) -> T:
    ...
```
Location: https://github.com/rspeer/ordered-set/blob/master/ordered_set.py#L90

The actual `__getitem__` has the `: int` definition, but that is ignored for type hinting if `@overload`s are used.

**Comment by rspeer** [comment]
This is true. When I added these overloads, MyPy said that the last overload should contain the concrete implementation; now it says that the concrete implementation should have no type signature. I'll fix this in the next version.

**Comment by rspeer** [comment]
Fixed in 4.1.
