### ISSUE TITLE
Please consider switching to flit_core

### ISSUE THREAD

**Issue by mgorny** [rspeer/ordered-set#82]
I'm the @Gentoo maintainer for core Python packages. We're currently considering options for bootstrapping setuptools while unvendoring its dependencies in the PEP 517 world. One of the interesting options is to use [flit](https://flit.readthedocs.io/en/latest/) as it has much fewer dependencies than setuptools and we've got its bootstrap trivially covered.

Using flit as ordered-set's build system would mean that we can cleanly install it before building setuptools. Flit can also generate a backwards-compatible `setup.py` (or be used alongside `setup.py`, though for this to work for us `pyproject.toml` would have to specify flit_core as the `build-backend`). FWICS it is becoming increasingly popular these days.

Would you be interested in this? If yes, then I can prepare a PR either converting the project to flit entirely, or adding it alongside existing `setup.py`, as you prefer.

**Comment by rspeer** [comment]
Sounds reasonable. I've been working on getting away from setuptools in some of my other projects, and part of the reason I've been reluctant to make ordered-set anything but a single module is that all the extra complexity seemed to come from setuptools.

I haven't tried flit yet, but I'm now familiar with `poetry`, and it's the first thing I've seen that makes me want to rework this package and the way it's installed. Would it help if I used poetry?

**Comment by mgorny** [comment]
Unfortunately, no. Poetry's got even worse dependency hell than setuptools.

**Comment by rspeer** [comment]
Sounds reasonable, but flit appears to forbid package names with hyphens in them.

Renaming the package someday is something to consider, given how its usage has diverged from Python's OrderedDict that came later. But then nobody would know about the new package.

**Comment by rspeer** [comment]
For what it's worth, it's been pretty clear over the years that it's a never-ending struggle to package even a single Python module in a way that meets everyone's needs, especially when the needs include "use setuptools" and "don't use setuptools". But maybe it's not necessary to meet everyone's needs with one packaging system.

Here's a possibly convenient thing about ordered-set: it's a single Python file. The original packaging was "here, copy this Python file into your package". setuptools weirdified it a bit, but it's still possible. Maybe gentoo can figure out packaging based on that.

**Comment by rspeer** [comment]
It looks like Flit once supported having a different `dist-name` than your importable package name, but it didn't make it into pyproject.toml? This is confusing.

**Comment by mgorny** [comment]
Unless I'm misunderstanding something, the following should work:

```toml
[project]
name = "ordered-set"

# ...

[tool.flit.module]
name = "ordered_set"
```

**Comment by mgorny** [comment]
> For what it's worth, it's been pretty clear over the years that it's a never-ending struggle to package even a single Python module in a way that meets everyone's needs, especially when the needs include "use setuptools" and "don't use setuptools". But maybe it's not necessary to meet everyone's needs with one packaging system.

I understand your point. However, there's no harm asking, right?

> Here's a possibly convenient thing about ordered-set: it's a single Python file. There's nothing that actually needs to be built. The packaging is all for the sake of building other things.
> 
> The original packaging was "here, copy this Python file into your package". setuptools weirdified it a bit, but it's still possible. Maybe gentoo has a way to wrap one python file in a Gentoo package for its own purposes.

Unfortunately, it's not that simple. Without the metadata generated by modern build systems the package won't be detected as installed and various packages depending on it via `install_requires` and their equivalents won't work.

**Comment by rspeer** [comment]
I do like flit's simplicity if it works. The settings you provided seem to do the job (though that was hard to find in their documentation).

**Comment by mgorny** [comment]
Not sure if we were looking at the same docs but it's under "New style metadata": https://flit.readthedocs.io/en/latest/pyproject_toml.html#new-style-metadata

> name
> The name your package will have on PyPI. This field is required. For Flit, this also points to your package as an import name by default (see [Module section](https://flit.readthedocs.io/en/latest/pyproject_toml.html#pyproject-module) if that needs to be different).

**Comment by arthurzam** [comment]
If it helps, I have written a full `pyproject.toml` file with flit backend. The information is taken from `setup.py`
I have taken my liberty and added classifiers until python 3.10
```toml
[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ordered-set"
version = "4.0.2"
description = "A set that remembers its order, and allows looking up its items by their index in that order."
authors = [
    {name = "Robyn Speer", email = "rspeer@luminoso.com"},
]
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[project.urls]
Home = "https://github.com/rspeer/ordered-set"

[tool.flit.module]
name = "ordered_set"

```

**Comment by rspeer** [comment]
I pushed 4.1, which uses flit. Thanks for the recommendation.

**Comment by mgorny** [comment]
Thank you! It works great ;-).
